@startuml
!include ../../style.puml
actor Alice
participant athens
participant byzantium
participant cyrene

Alice -> athens : set "title", "Microservices"
athens -> athens  : set "title", "Microservices"
note over athens
"title":"Microservices"
end note
athens -[#red]>x byzantium  : <:fire:> set "title", "Microservices"
note over byzantium
end note
athens -> cyrene  : set "title", "Microservices"
note over cyrene
"title":"Microservices"
end note
athens -> athens : isQuorumReached
athens --> Alice : Success

@enduml
