@startuml
!include ../../style.puml
actor Alice
box "Cluster" #E6F3FF
participant athens
participant byzantium
participant cyrene
end box

Alice -> athens : set "title", "After Dawn"
athens -> athens  : set "title", "After Dawn"
note over athens
"title":"After Dawn"
end note
athens -[#red]>x byzantium  : <:fire:> set "title", "After Dawn"
note over byzantium
end note
athens -> cyrene  : set "title", "After Dawn"
note over cyrene
"title":"After Dawn"
end note
athens -> athens : isQuorumReached
athens --> Alice : Success

@enduml
