@startuml
!include ../../style.puml
actor Alice
box "Cluster" #E6F3FF
participant athens
participant byzantium
participant cyrene
end box

note over athens
"title":"After Dawn"
end note
/ note over cyrene
"title":"After Dawn"
end note

Alice -> athens : get "title"
athens -> athens  : get "title"
athens <-- athens : "After Dawn"

athens -> byzantium  : get "title"
athens <-- byzantium : ""

athens -[#red]>x cyrene  : <:fire:> get "title"

athens -> athens : isQuorumReached
athens --> Alice : After Dawn

@enduml
