@startuml
!include ../../style.puml

' [common]
actor Alice
actor Bob
box "Cluster" #E6F3FF
participant athens
participant byzantium
participant cyrene
end box
participant Nemesis
participant Checker
'[/common]
note over athens, cyrene
  **Inital State**
  | title | Before Dawn |
end note

' [step1 {"name":"Client Write Starts"}]
Alice -> athens : set("title", "After Dawn")
activate athens
' [/step1]

' [step2 {"name":"Write Reaches Majority"}]
athens -> byzantium : replicate write
' [/step2]

' [step3 {"name":"Majority Ack"}]
byzantium --> athens : ack
' [/step3]

' [step4 {"name":"Nemisis crashes cyrene"}]
Nemesis -[#red]>x cyrene : partition / crash
' [/step4]

' [step5 {"name":"Minority Misses Write"}]
athens -[#red]>x cyrene : <:fire:>replicate write
' [/step5]

' [step6 {"name":"Client Sees Success"}]
athens --> Alice : success
deactivate athens
' [/step6]

' [step7 {"name":"Fault Is Injected"}]
Nemesis -[#red]> athens : partition / pause / delay
' [/step7]

' [step8 {"name":"Another Client Reads"}]
Bob -> cyrene : get("title")
' [/step8]

' [step9 {"name":"Client Sees Old Value"}]
cyrene --> Bob : "Before Dawn" ?
' [/step9]

' [step10 {"name":"Checker Sees Read History"}]
Bob -> Checker : observed read history
' [/step10]

' [step11 {"name":"Checker Sees Write History"}]
Alice -> Checker : observed write history
' [/step11]

note over cyrene, Checker
Focus:
what value did clients observe,
and is that history still correct?
end note

@enduml
