@startuml
skinparam Shadowing false

skinparam cloud {
    BackgroundColor #E0F2FF
    BorderColor Black
}

skinparam node {
    BackgroundColor White
    BorderColor Black
    RoundCorner 20
}

skinparam note {
    BackgroundColor PaleGoldenRod
    BorderColor Black
}

title **Need to Manage Cluster Metadata/Configuration**

cloud "Scalable Cluster" {
    
    node "<:crown:> Server-1 (Controller)\nMaintains Partition/Task Assignments" as S1 #LightGreen

    node "Server-2\nPartitions: 1,4" as S2 #LightGreen
    node "Server-3\nPartitions: 2,5" as S3 #LightGreen
    node "Server-4\nPartitions: 3,6" as S4 #LightGreen
    node "Server-998\nPartitions: 994,997" as S998 #LightGreen
    node "Server-999\nPartitions: 995,998" as S999 #LightGreen
    node "Server-1000\nPartitions: 996,999" as S1000 #LightGreen

    S1 -down-> S2 : Monitor
    S1 -down-> S3 : Monitor
    S1 -down-> S4 : Monitor
    S1 -down-> S998 : Monitor
    S1 -down-> S999 : Monitor
    S1 -down-> S1000 : Monitor

    note right of S1
        **Partition Map Registry**  
        | Node ID   | Hosted Partitions/Tasks |
        |-----------|-----------------------|
        | Server-2  | 1,4   |
        | Server-3  | 2,5   |
        | Server-4  | 3,6   |
        | Server-998 | 994,997 |
        | Server-999 | 995,998 |
        | Server-1000 | 996,999 |
    end note
}
@enduml
