@startuml
!include ../style.puml

participant Client
note over Client: HybridClock: (1000, 0)
/ note over Blue: HybridClock: (1000, 0)

'[step]
Client -> Blue: write("name", "Alice", "timestamp=(1000,0)")
'[step]
Blue -> Blue: merge((1000,0))
note right of Blue
  Read local clock: now = 1000
  Pick largest of request timestamp or local clock
  If same as previous latestTime, increment 
  logical counter
  Result: (1000, 1)
end note
'[step]
note over Blue 
HybridClock: (1000, 1)
key: "name@(1000,1)"
value: "Alice"
end note
'[step]
Client <-- Blue: writtenAt (1000, 1)
'[step]
note over Client: HybridClock: (1000, 1)
'[step]
note over Green: HybridClock: (1005, 0)
'[step]
Client -> Green: write("title", "Microservices", "timestamp=(1000,1)")
'[step]
Green -> Green: merge((1000,1))
'[step]
note right of Green
  Read local clock: now = 1005
  Pick largest of request timestamp or local clock
  → newLogical = 0
  Result: (1005, 0)
end note
'[step]
note over Green 
HybridClock: (1005, 0)
key: "title@(1005,0)"
value: "Microservices"
end note
'[step]
Client <-- Green: writtenAt (1005, 0)
note over Client: HybridClock: (1005, 0)
'[step]

@enduml

