@startuml
!include ../style.puml

' [step1 {"name":"Multiple Brokers Register"}]
participant "Broker 1" as b1
participant "Broker 2" as b2
participant "Broker 3" as b3
participant "ZooKeeper" as zk
b1 -> zk: Register broker (id=1)
' [/step1]

' [step2]
b2 -> zk: Register broker (id=2)
' [/step2]

' [step3]
b3 -> zk: Register broker (id=3)
' [/step3]

@enduml
