@startuml
!include ../style.puml

' [step1 {"name":"Three Broker Cluster"}]
participant "Broker 1" as b1
participant "Broker 2" as b2
participant "Broker 3" as b3
participant "ZooKeeper" as zk
participant "Admin Client" as client
' [/step1]

' [step2 {"name":"Brokers run election", "newPage":"true"}]
group  #LightGreen "Controller Election"
b1 -> zk: Try create /controller znode
activate b1
zk -> b1: Success
' [/step2]

' [step3]
b2 -> zk: Try create /controller znode
activate b2
b3 -> zk: Try create /controller znode
activate b3
'[/step3]

' [step4]
zk -> b2: Failure
zk -> b3: Failure
note right of b1: Becomes Controller
end
' [/step4]

' [step5 {"name":"Controller Initialization", "newPage":"true"}]
group #LightYellow "Controller Initialization" 
b1 -> b1: Initialize 
' [/step5]

' [step6]
b1 -> zk: Load broker metadata

' [/step6]

' [step7]
b1 -> zk: Subscribe to topic changes
deactivate b1
end
' [/step7]

@enduml
