
@startuml
!include ../style.puml

' [step1 {"name":"Three Broker Cluster"}]
participant "Broker 1" as b1
participant "Broker 2" as b2
participant "Broker 3" as b3
participant "ZooKeeper" as zk
participant "Admin Client" as client
' [/step1]

' [step2 {"name":"Topic Creation"}]
group #LightPink "Topic Creation" 
client -> AdminUtils: Create topic "test"\n(3 partitions, RF=3)     
' [/step2]

' [step3]
AdminUtils -> AdminUtils: AssignPartitionsToBrokers\n(P0: [1,2,3], P1: [2,3,1], P2: [3,1,2])     
' [/step3]


' [step4]
AdminUtils -> zk: Store topic metadata\n(P0: [1,2,3], P1: [2,3,1], P2: [3,1,2])
end
' [/step4]

' [step5]
zk -> b1: Topic change callback
activate b1
' [/step5]

' [step6]
group #LightCoral "Controller notifies brokers" 
b1 -> b1: Elect leaders for partitions\nP0: Leader=1, Replicas=[1,2,3]\nP1: Leader=2, Replicas=[2,3,1]\nP2: Leader=3, Replicas=[3,1,2]
' [/step6]

' [step7]
b1 -> b1: LeaderAndIsr Request\n(P0: Leader, P1: Follower, P2: Follower)
' [/step7]

' [step8]
b1 -> b2: LeaderAndIsr Request\n(P0: Follower, P1: Leader, P2: Follower)
' [/step8]

' [step9]
b1 -> b3: LeaderAndIsr Request\n(P0: Follower, P1: Follower, P2: Leader)
' [/step9]

' [step10]  
b1 -> b1: UpdateMetadata Request
' [/step10]

' [step11]
b1 -> b2: UpdateMetadata Request
' [/step11]

' [step12]
b1 -> b3: UpdateMetadata Request
deactivate b1
end
' [/step12]
@enduml