@startuml
!include ../style.puml
title **Handling LeaderAndIsrRequest in Kafka Broker**
'[step1 {"name":"Controller sends LeaderAndIsrRequest to the Broker"}]
participant "Kafka Controller/Broker1" as controller #LightCoral
participant "Broker" as broker #LightSteelBlue
participant "Partition" as partition #LightGreen
participant "Log File" as log #LightGray
'[/step1]

' [step2]
controller -> broker : LeaderAndIsrRequest (P0, P1)
activate broker

group "Broker checks its role"
    broker -> broker : Is this broker the leader?
    alt If Leader
        broker -> partition : Create Partition (P0)
        partition -> log : Create Log File
        note right of log
            | Log File |
            |---------|
            |   |
            |   |
            |   |
        end note
    else If Follower
        broker -> partition : Create Partition (P1)
        partition -> log : Create Log File
        note right of log
            | Log File |
            |---------|
            |   |
            |   |
            |   |
        end note
        broker -> broker : Create Fetcher Task
    end
end

deactivate broker
'[/step2]
@enduml
