!$back = "#F7F8FE"
!$border = "#070D4A"
!$lightyellow = "#FFFFE0"
!procedure $box()
  skinparam Shadowing true
  skinparam RoundCorner 10
  skinparam DefaultFontName "Roboto"
  skinparam DefaultFontSize 14
  skinparam DefaultFontColor Black
  skinparam ParticipantBackgroundColor White
  skinparam ParticipantBorderColor Black
  skinparam SequenceLifeLineBorderColor Gray
  skinparam SequenceLifeLineBackgroundColor LightGray
  skinparam LifelineStrategy solid
!endprocedure

skinparam shadowing false
skinparam sequenceParticipant{
  $box()
}
skinparam sequenceLifeLine {
 $box()
}
skinparam sequence {
  ArrowColor $border
}

skinparam Note {
  BackgroundColor $lightyellow
}
skinparam Node {
  $box()
}

skinparam object {
  $box()
}

skinparam actor {
  $box()
}

skinparam dpi 600

hide footbox
